services:
  postgres:
    image: postgres:16-alpine
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DB_POOL_SIZE: ${DB_POOL_SIZE}
      SPRING_DB_CONNECTION_TIMEOUT: ${DB_CONNECTION_TIMEOUT}
      # R2DBC alternative:
      # SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/appdb
      # SPRING_R2DBC_USERNAME: ${POSTGRES_USER}
      # SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "8080:8080"   # expose API to your host browser/Postman

volumes:
  pgdata:
