spring:
  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver     # optional, but explicit is fine

    hikari:
      maximum-pool-size: ${SPRING_DB_POOL_SIZE}
      connection-timeout: ${SPRING_DB_CONNECTION_TIMEOUT}

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  metrics:
    tags:
      app: spring-threads-benchmarks
      profile: ${spring.profiles.active:local}
      run: ${RUN_ID:dev}
    distribution:
      percentiles-histogram:
        db.find_by_id: true
        db.create_order: true
        db.slow_query: true
