global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - backend:8080   # access host from Docker on macOS/Windows
        labels:
          app: spring-threads-bench