events {}

http {
    upstream runner_upstream {
        server runner:8081;
    }

    upstream grafana_upstream {
        server grafana:3000;
    }

    upstream frontend_upstream {
        server frontend:8082;
    }

    server {
        listen 80;
        server_name _;

        # Proxy Runner API
        location ^~ /runs {
            proxy_pass http://runner_upstream;
            proxy_http_version 1.1;
            proxy_set_header Host           $host;
            proxy_set_header X-Real-IP      $remote_addr;
        }

        location ^~ /grafana {
          proxy_pass http://grafana_upstream;
          proxy_http_version 1.1;
          proxy_set_header Host              $host;   # keeps :80/:443 if present
          proxy_set_header X-Real-IP         $remote_addr;
          #proxy_set_header X-Forwarded-Host  $http_host;
          #proxy_set_header X-Forwarded-Proto $scheme;
          #proxy_set_header X-Forwarded-Prefix /grafana;
          # proxy_redirect off;  # remove or leave off; not required here
        }

        # --- Frontend fall back ---
        location / {
          proxy_pass http://frontend_upstream;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Upgrade $http_upgrade;
          proxy_read_timeout 60s;
        }
    }
}
